services:
  - type: web
    name: pneumonia-detection
    runtime: python
    env: python
    pythonVersion: 3.10
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi:application
